import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { RouterModule } from '@angular/router';
import { JhiTrackerService } from './../shared/tracker/tracker.service';

import { AvonnivSharedModule } from '../shared';
/* jhipster-needle-add-admin-module-import - JHipster will add admin modules imports here */

import {
    adminState,
    AuditsComponent,
    AreaMgmtComponent,
    AreaDialogComponent,
    AreaDeleteDialogComponent,
    AreaMgmtDialogComponent,
    AreaMgmtDeleteDialogComponent,
    UserMgmtComponent,
    UserDialogComponent,
    UserDeleteDialogComponent,
    UserMgmtDetailComponent,
    UserMgmtDialogComponent,
    UserMgmtDeleteDialogComponent,
    PublisherMgmtComponent,
    PublisherDialogComponent,
    PublisherDeleteDialogComponent,
    PublisherMgmtDetailComponent,
    PublisherMgmtDialogComponent,
    PublisherMgmtDeleteDialogComponent,
    LogsComponent,
    JhiMetricsMonitoringModalComponent,
    JhiMetricsMonitoringComponent,
    JhiHealthModalComponent,
    JhiHealthCheckComponent,
    JhiConfigurationComponent,
    JhiDocsComponent,
    AuditsService,
    JhiConfigurationService,
    JhiHealthService,
    JhiMetricsService,
    JhiTrackerComponent,
    LogsService,
    AreaResolvePagingParams,
    AreaResolve,
    AreaModalService,
    PublisherResolvePagingParams,
    PublisherResolve,
    PublisherModalService,
    UserResolvePagingParams,
    UserResolve,
    UserModalService
} from './';

@NgModule({
    imports: [
        AvonnivSharedModule,
        RouterModule.forRoot(adminState, { useHash: true }),
        /* jhipster-needle-add-admin-module - JHipster will add admin modules here */
    ],
    declarations: [
        AuditsComponent,
        UserMgmtComponent,
        UserDialogComponent,
        UserDeleteDialogComponent,
        UserMgmtDetailComponent,
        UserMgmtDialogComponent,
        UserMgmtDeleteDialogComponent,
        AreaMgmtComponent,
        AreaDialogComponent,
        AreaDeleteDialogComponent,
        AreaMgmtDialogComponent,
        AreaMgmtDeleteDialogComponent,
        PublisherMgmtComponent,
        PublisherDialogComponent,
        PublisherDeleteDialogComponent,
        PublisherMgmtDetailComponent,
        PublisherMgmtDialogComponent,
        PublisherMgmtDeleteDialogComponent,
        LogsComponent,
        JhiConfigurationComponent,
        JhiHealthCheckComponent,
        JhiHealthModalComponent,
        JhiDocsComponent,
        JhiTrackerComponent,
        JhiMetricsMonitoringComponent,
        JhiMetricsMonitoringModalComponent
    ],
    entryComponents: [
        UserMgmtDialogComponent,
        UserMgmtDeleteDialogComponent,
        AreaMgmtDialogComponent,
        AreaMgmtDeleteDialogComponent,
        PublisherMgmtDialogComponent,
        PublisherMgmtDeleteDialogComponent,
        JhiHealthModalComponent,
        JhiMetricsMonitoringModalComponent,
    ],
    providers: [
        AuditsService,
        JhiConfigurationService,
        JhiHealthService,
        JhiMetricsService,
        LogsService,
        JhiTrackerService,
        AreaResolvePagingParams,
        AreaResolve,
        AreaModalService,
        PublisherResolvePagingParams,
        PublisherResolve,
        PublisherModalService,
        UserResolvePagingParams,
        UserResolve,
        UserModalService
    ],
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class AvonnivAdminModule {}
